name: Go package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Run coverage
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

#      - name: Coveralls GitHub Action
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
      - name: Get path to lcov file
        id: get_lcov_path
        shell: bash
        run: printf '::set-output name=lcov_path::%s\n' TestResults/*/coverage.info
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.get_lcov_path.outputs.lcov_path }}