name: Quality
on:
  pull_request:
    paths:
      - 'subber/**'
      - 'go.mod'
jobs:
  service:
    name: Subber Workflows
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go mod download
      - name: Run Unit tests
        run: |
          go test -race -covermode atomic -coverprofile=covprofile ./subber/...
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          flag-name: adder
          config-file: .coveralls.yml
        run: goveralls -coverprofile=covprofile -service=github
